### ISSUE TITLE
Object Storage

### ISSUE THREAD

**Issue by joshualjohnson** [fire015/flintstone#24]
Noticed that Flintstone doesn't currently support object storage per key but will support an object loaded into an array. 

Should there be support for object storage directly?

**Comment by TheDigitalOrchard** [comment]
You could serialize the objects and store that as a string value.

**Comment by joshualjohnson** [comment]
Flintstone will already do that for you. If you store an array with one object in it, FlintstoneDB will serialize the object when it stores. But then I am storing an array with an object. 

I think Flintstone can support storing Objects directly relatively easy. Wanted to see if you guys agreed. That way a User key could be associated with a User object.

**Comment by joshualjohnson** [comment]
It looks to me that Flintstone already supports storing objects directly. I will fork update the datatype check to remove the this restriction.

**Comment by joshualjohnson** [comment]
Im going to look into this again and see if I can get it working. I think this would be a great addition to this piece of software!

**Comment by fire015** [comment]
Interesting piece of code from Laravel... https://github.com/laravel/framework/blob/5.0/src/Illuminate/Queue/SerializesModels.php

**Comment by joshualjohnson** [comment]
Hmmm...That looks interesting! I'll take a look at this

**Comment by joshualjohnson** [comment]
So the problem is with an associative array! We can't store an associative array in Json. It is physically impossible. So I think instead of just allowing the data to be stored, there should be a constraint to now allow you to store associative arrays in a JSON format. This makes sense to me. Any thoughts?
