### ISSUE TITLE
Cannot add key/value to same ID

### ISSUE THREAD

**Issue by Crank1d** [fire015/flintstone#27]
Im trying to create simple page views log system for my website which works on daily basis. Date (year,month,day) is used as key.

post-1={
    "2015-10-18": 52
}

Incrementing value by 1, per each page view works (when key matches current date or is smaller than current date), but when I try to add new key/value (date, day views) to "post-1" or any other, key/value gets overwritten instead of being added to JSON array. For example whole array looks like that above, but when date is changed, that "2015-10-18" is changed to current date and value is reset to zero, instead of pushing new date into array. Does that happen because of Flintstone DB limitations or am I doing something wrong with JSON?

**Comment by fire015** [comment]
This is not how it works, Flintstone overrides the whole value so you would have to send the full array.
