### ISSUE TITLE
flintstone Injections

### ISSUE THREAD

**Issue by renat2985** [fire015/flintstone#31]
For flintstone need to filter some symbols that can damage the database?

**Comment by fire015** [comment]
I don't understand, can you please provide some samples.

**Comment by fire015** [comment]
Closing this ticket unless further details are provided.

**Comment by Soaku** [comment]
@fire015 He means, if there are any symbols that need to be escaped before inserting to Flintstone. 

@renat2985 I guess, Flintstone does this automatically.
