### ISSUE TITLE
set returns void instead of bool

### ISSUE THREAD

**Issue by Suven** [fire015/flintstone#35]
Hi!

I'm currently writing [a wrapper](https://github.com/Suven/flintRedis) around flintstone/redis and noticed a little difference between your docs and implementation.

The docs state 
> Set data for the key name. Data can be a string, integer, float or array. Returns true or will throw an exception if fails to set.

But in reality, `set` [isn't returning true](https://github.com/fire015/flintstone/blob/master/src/Flintstone.php#L154)

**Comment by fire015** [comment]
Thanks for spotting, I have now updated the docs on http://www.xeweb.net/flintstone/documentation/
