### ISSUE TITLE
Unserialize Notice

### ISSUE THREAD

**Issue by MrManchot** [fire015/flintstone#36]
Hello,

I don't know if I'm doing something anormal, but I have several notice with Flintstone :

unserialize(): Error at offset ** of ** bytes in /***/vendor/fire015/flintstone/src/Formatter/SerializeFormatter.php on line 29

Regards

**Comment by fire015** [comment]
This is usually caused by UTF-8 or another character set messing up the serialize function. Would recommend you use the JSON formatter instead, see https://github.com/fire015/flintstone#changing-the-formatter

**Comment by MrManchot** [comment]
Thank you !
