### ISSUE TITLE
Use magic methods

### ISSUE THREAD

**Issue by Soaku** [fire015/flintstone#38]
So, there are 6 main methods in Flintstone. 

- get
- set
- remove
- flush
- getKeys
- getAll

Even 4 of them can be replaced with better, PHP's build-in [magic methods]. That would make use of Flintstone easier and more efficient. Few stuff to do:

- Rename `get` to `__get`,  `set` to `__set`
- Rename `remove` to `__unset`
- Rename `flush` to `__destruct`
- Make `get`, `set` and `remove` synonymous to their new names.

  ```
  function get($k, $v){$this->__get($k, $v)}
  ```

  etp.
- Add `flush` function to do nothing (as PHP will automatically flush the database when shutting down, that's how `__destruct` works)
- You might also want to add `__isset` to check if key exists.

This will simplify the syntax:

````
$db->key = "value";
$db->{"key with special chars"} = "value";
echo $db->key;

unset($db->key); # Remove key
var_dump(isset($db->key)) # Check if it's set.

# Notice there is now no need to add $db->flush();
````

As a bonus, it will add a possibility to create DB references, which would be amazing feature, that doesn't exist in SQL, for example.

```
$ref =& $db->key; # Reference var $ref to key `key`
$ref = "Hello ";
$ref .= "World!";
echo $db->key; # Hello World!
```

That's not all yet. You would have possibility to use special assign operators like `+=` etp.:

```
$db->key += 5;
```

Would be really nice to see it in the database. It's not hard to add prefixes and synonymous functions, isn't it? I'm already trying to do it on local version on Flintstone.php file.

Thanks.

[magic methods]: http://php.net/manual/en/language.oop5.magic.php

**Comment by fire015** [comment]
Sorry I dont think this is a good idea, there's too much ambiguity with this approach. Plus changing variables this way would require saving each time which would be an expensive operation.
