### ISSUE TITLE
location of database?

### ISSUE THREAD

**Issue by persianphilosopher** [fire015/flintstone#41]
My apologies if this is addressed but I could not find it in the issues or the code. I am wondering if it is possible to optionally pass the location of the database in the __construct. Because I run different scripts and operations on my "notes" folder, I would like to avoid having the notes.dat be located in the same folder.  Thank you greatly

**Comment by fire015** [comment]
Hi, you can pass the path to the folder you want in the constructor like so...

    $notes = new Flintstone('notes', ['dir' => '/foo/blah/data']);

This would store the file in /foo/blah/data/notes.dat
